// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rszhqgoewlppryinpwnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzemhxZ29ld2xwcHJ5aW5wd25rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDk5MTgsImV4cCI6MjA3NDM4NTkxOH0.g97wy8snNb63DL9-ay8woEf7-AeMWKhhK7aciCOw0M8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});